#!/bin/bash

p="tilux"
p2="get_ip"
p3="idbf"
p4="hosts"

if [ ! -d "$p" ]; then
  echo "Installing $p"
  git clone https://github.com/endormi/$p
  echo "Done!"
else
  echo "$p Already exists!"
fi

if [ ! -d "$p2" ]; then
  echo "Installing $p2"
  git clone https://github.com/endormi/$p2
  echo "Done!"
else
  echo "$p2 Already exists!"
fi

if [ ! -d "$p3" ]; then
  echo "Installing $p3"
  git clone https://github.com/0x020/$p3
  echo "Done!"
else
  echo "$p3 Already exists!"
fi

if [ ! -d "$p4" ]; then
  echo "Installing $p4"
  git clone https://github.com/0x020/$p4
  echo "Done!"
else
  echo "$p4 Already exists!"
fi
