#!/bin/bash

p="tilux"
p2="get_ip"
p3="idbf"
p4="hosts"
p5="find_domain_ip"
p6="automation"
p7="emacs-init"

if [ ! -d "$p" ]; then
  if [[ `lsb_release -d | grep 'Ubuntu'` != 0 ]]; then
    echo "Installing $p"
    git clone https://github.com/endormi/$p.git
    echo "Done!"
  fi
else
  echo "$p Already exists!"
fi

if [ ! -d "$p2" ]; then
  echo "Installing $p2"
  git clone https://github.com/0x020/$p2.git
  echo "Done!"
else
  echo "$p2 Already exists!"
fi

if [ ! -d "$p3" ]; then
  echo "Installing $p3"
  git clone https://github.com/0x020/$p3.git
  echo "Done!"
else
  echo "$p3 Already exists!"
fi

if [ ! -d "$p4" ]; then
  echo "Installing $p4"
  git clone https://github.com/0x020/$p4.git
  echo "Done!"
else
  echo "$p4 Already exists!"
fi

if [ ! -d "$p5" ]; then
  echo "Installing $p5"
  git clone https://github.com/endormi/$p5.git
  echo "Done!"
else
  echo "$p5 Already exists!"
fi

if [ ! -d "$p6" ]; then
  echo "Installing $p6"
  git clone https://github.com/endormi/$p6.git
  echo "Done!"
else
  echo "$p6 Already exists!"
fi

if [ ! -d "$p7" ]; then
  if [ -d "$HOME/.emacs.d" ]; then
    echo "Installing $p7"
    git clone https://github.com/endormi/$p7.git
    echo "Done!"
  fi
else
  echo "$p7 Already exists!"
fi
